# Generated by Django 5.0.6 on 2024-07-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_course_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
